CREATE DATABASE [Police]
GO
USE [Police]
GO
CREATE TABLE [User]
(
[ID] INT PRIMARY KEY IDENTITY,
[FirstName] NVARCHAR(50) NOT NULL,
[SurName] NVARCHAR(50) NOT NULL,
[LastName] NVARCHAR(50),
[RankID] INT FOREIGN KEY REFERENCES[Rank](ID) NOT NULL
)
GO
CREATE TABLE [Rank]
(
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,

)
GO
CREATE TABLE [Authorization]
(
[ID] INT PRIMARY KEY IDENTITY,
[Login] NVARCHAR(50) NOT NULL,
[Password] NVARCHAR(50) NOT NULL,
[UserID] INT FOREIGN KEY REFERENCES [User](ID) NOT NULL
)
GO 
CREATE TABLE [Functional]
(
[ID] INT PRIMARY KEY IDENTITY, 
[Capability] NVARCHAR(50) NOT NULL,
[Work] NVARCHAR(50) NOT NULL,
[RankID] INT FOREIGN KEY REFERENCES[Rank](ID) NOT NULL
)
